### ISSUE TITLE
Tests are reported in different order than they're defined in

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/ruby-test-runner#33]
Hi 👋 I started testing some Ruby concept exercises and at log-line-parser I got a bit annoyed that the first test failure is about the `log_level` method from the second task instead of the `message` method from the first task. I checked the exercise (https://github.com/exercism/ruby/blob/main/exercises/concept/log-line-parser/log_line_parser_test.rb#L7-L21) and there the tests are implemented in the same order as tasks, so I am concluding this is a bug in the test runner.

**Comment by iHiD** [comment]
Thanks 🙂  

Yeah. Minitest doesn't support this, so I need to do it manually and haven't done it yet. (I'd forgotten I hadn't - so this is a super-helpful reminder).

The way I plan to do this is `lib/minitest_ext/exercism_reporter.rb`, within `report`, sort the `tests` by the order they appear in the corresponding test file. I'm not sure what data is in the `result` object at that stage, so may also need to add further info into that further up.

If you'd like to give it a go, then I'll happily accept a PR. Otherwise I'll do it soon 🙂

**Comment by angelikatyborska** [comment]
I managed to come up with something 🙂
