### ISSUE TITLE
Bowling tests fail, giving message "AN ERROR OCCURED"

### ISSUE THREAD

**Issue by justisCrocker** [exercism/ruby-test-runner#54]
I have submitted my code a number of times as is suggested, but every time the testing fails completely. The tests run and complete as expected locally. I am using Ruby 2.6.8, and have not made any modifications to my local copy of bowling_test.rb.

**Comment by kotp** [comment]
So, given you have made no modifications to the local copy of `bowling_test.rb` when ran locally, you may have  result of one test passing, the rest skipped.  You are expected to modify the local copy of the test file for practice exercises.

If you submit the exercise and request mentoring, I will keep my eye on the queue and hopefully can help out.  If not me, then another mentor will likely be able to assist.

Also;

> Ruby 2.6
status: security maintenance
release date: 2018-12-25
EOL date: 2022-03-31

So if possible, though not related, I am pretty sure, you may want to upgrade your Ruby as it ended its life-cycle a couple of days ago.

**Comment by justisCrocker** [comment]
Have my Ruby all updated now, thanks for the tip. And I definitely don't have any tests skipped, see image for proof. I will request mentoring on this, since the problem continues.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/48866294/161403416-df6efa7a-9fa6-409e-af07-6584b70ece18.png">

**Comment by justisCrocker** [comment]
I found the issue, as usual it is obvious in hindsight. I had used Pry for debugging, and Exercism's test runner didn't like my "require 'pry'" line. Removed the line and submitted no problem.

**Comment by kotp** [comment]
One way to do this is as I wrote in the instructions for the `pride` functionality.  You can do `ruby -rpry -rminitest/pride something_test.rb` and have pry available, without leaving debugging cruft in your code.  The other benefit is that if you forget to remove the debugging it screams loudly because the library is not available, reminding you to either guard it with the `$DEBUG` which is switchable from the command line via a flag as well, or to remove them.

I am glad you figured it out.
